version: '3'

services:
  db:
    container_name: postgres_database
    image: postgres:15.1
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin1945
    ports:
      - "5432:5432" # To expose the container to the localhost

  pgAdmin:
    depends_on:
      - db
    image: dpage/pgadmin4:6.17
    ports:
      - "8080:80" # Port 80 must be exposed to the localhost
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_PASSWORD=admin1945
      - PGADMIN_DEFAULT_EMAIL=admin@unam.mx

  flask_app:
    build: ./flaskr  # Flask files
    ports:
      - "5000:5000"  # Flask port
    environment:
      - DATABASE_URL=postgresql://postgres:admin1945@db:5432/Qwikz
    depends_on:
      - db